import { readFileSync, writeFileSync, existsSync, unlinkSync, rmdirSync, rmSync } from 'fs';
import { resolve, join } from 'path';
import os from 'os';
import { loadManifest } from './validate.js';
import { log } from '../utils/logger.js';
import chalk from 'chalk';

/**
 * Remove pack MCP servers from an MCP config file, preserving others.
 */
function unmergeMcpConfig(filePath, serverIds) {
  if (!existsSync(filePath)) return 0;

  try {
    const config = JSON.parse(readFileSync(filePath, 'utf-8'));
    if (!config.mcpServers) return 0;

    let removed = 0;
    for (const id of serverIds) {
      if (config.mcpServers[id]) {
        delete config.mcpServers[id];
        removed++;
      }
    }

    if (removed > 0) {
      writeFileSync(filePath, JSON.stringify(config, null, 2), 'utf-8');
    }
    return removed;
  } catch {
    return 0;
  }
}

export async function cleanCommand(path, options = {}) {
  try {
    const { manifest } = loadManifest(path);
    const targetDir = resolve(options.cwd || '.');
    const targetClient = (options.target || 'all').toLowerCase();

    console.log();
    console.log(chalk.bold.red(`🧹 AIPack Safe De-Provisioner: ${manifest.name}`));
    console.log(chalk.dim(`Cleaning from: ${targetDir}`));
    console.log();

    let itemsCleaned = 0;
    const serverIds = (manifest.tools?.mcp_servers || []).map(s => s.id || s.name);

    // --- Clean Claude Code / Desktop ---
    if (targetClient === 'all' || targetClient === 'claude') {
      // 1. Subagents
      if (manifest.agents) {
        for (const agent of manifest.agents) {
          const agentFile = join(targetDir, '.claude', 'agents', `${agent.id}.md`);
          if (existsSync(agentFile)) {
            unlinkSync(agentFile);
            console.log(`  ${chalk.red('✗ Removed:')} .claude/agents/${agent.id}.md`);
            itemsCleaned++;
          }
        }

        // Try removing agents directory if empty
        const agentsDir = join(targetDir, '.claude', 'agents');
        try {
          if (existsSync(agentsDir)) rmdirSync(agentsDir);
        } catch {
          // not empty, that's fine
        }
      }

      // 2. CLAUDE.md (safe check)
      const claudeMdPath = join(targetDir, 'CLAUDE.md');
      if (existsSync(claudeMdPath)) {
        const content = readFileSync(claudeMdPath, 'utf-8');
        const isPackGenerated = (content.includes('aipack') && content.includes(manifest.name)) || options.force;
        if (isPackGenerated) {
          unlinkSync(claudeMdPath);
          console.log(`  ${chalk.red('✗ Removed:')} CLAUDE.md`);
          itemsCleaned++;
        } else {
          console.log(`  ${chalk.yellow('⚠ Skipped:')} CLAUDE.md (contains modifications or not generated by this pack. Use --force to delete)`);
        }
      }

      // 3. MCP servers in .mcp.json and .claude/settings.json
      if (serverIds.length > 0) {
        const removedRoot = unmergeMcpConfig(join(targetDir, '.mcp.json'), serverIds);
        if (removedRoot > 0) {
          console.log(`  ${chalk.red('✗ Pruned:')} ${removedRoot} servers from .mcp.json`);
          itemsCleaned += removedRoot;
        }
        const removedClaude = unmergeMcpConfig(join(targetDir, '.claude', 'settings.json'), serverIds);
        if (removedClaude > 0) {
          console.log(`  ${chalk.red('✗ Pruned:')} ${removedClaude} servers from .claude/settings.json`);
          itemsCleaned += removedClaude;
        }

        if (os.platform() === 'darwin') {
          const desktopConfigPath = join(os.homedir(), 'Library', 'Application Support', 'Claude', 'claude_desktop_config.json');
          if (existsSync(desktopConfigPath)) {
            const removedDesktop = unmergeMcpConfig(desktopConfigPath, serverIds);
            if (removedDesktop > 0) {
              console.log(`  ${chalk.red('✗ Pruned:')} ${removedDesktop} servers from Claude Desktop App`);
              itemsCleaned += removedDesktop;
            }
          }
        }
      }
    }

    // --- Clean Cursor ---
    if (targetClient === 'all' || targetClient === 'cursor') {
      const cursorrulesPath = join(targetDir, '.cursorrules');
      if (existsSync(cursorrulesPath)) {
        const content = readFileSync(cursorrulesPath, 'utf-8');
        const isPackGenerated = (content.includes('aipack') && content.includes(manifest.name)) || options.force;
        if (isPackGenerated) {
          unlinkSync(cursorrulesPath);
          console.log(`  ${chalk.red('✗ Removed:')} .cursorrules`);
          itemsCleaned++;
        } else {
          console.log(`  ${chalk.yellow('⚠ Skipped:')} .cursorrules (contains custom modifications. Use --force to delete)`);
        }
      }

      // Clean modular .cursor/rules/*.mdc
      if (manifest.agents) {
        for (const agent of manifest.agents) {
          const ruleFile = join(targetDir, '.cursor', 'rules', `${agent.id}.mdc`);
          if (existsSync(ruleFile)) {
            unlinkSync(ruleFile);
            console.log(`  ${chalk.red('✗ Removed:')} .cursor/rules/${agent.id}.mdc`);
            itemsCleaned++;
          }
        }
        const cursorRulesDir = join(targetDir, '.cursor', 'rules');
        try {
          if (existsSync(cursorRulesDir)) rmdirSync(cursorRulesDir);
        } catch {
          // not empty
        }
      }

      if (serverIds.length > 0) {
        const removed = unmergeMcpConfig(join(targetDir, '.cursor', 'mcp.json'), serverIds);
        if (removed > 0) {
          console.log(`  ${chalk.red('✗ Pruned:')} ${removed} servers from .cursor/mcp.json`);
          itemsCleaned += removed;
        }
      }
    }

    // --- Clean AGENTS.md (Universal) ---
    if (targetClient === 'all' || targetClient === 'agentsmd') {
      const agentsMdPath = join(targetDir, 'AGENTS.md');
      if (existsSync(agentsMdPath)) {
        const content = readFileSync(agentsMdPath, 'utf-8');
        const isPackGenerated = (content.includes('aipack') && content.includes(manifest.name)) || options.force;
        if (isPackGenerated) {
          unlinkSync(agentsMdPath);
          console.log(`  ${chalk.red('✗ Removed:')} AGENTS.md`);
          itemsCleaned++;
        }
      }
    }

    // --- Clean Windsurf ---
    if (targetClient === 'all' || targetClient === 'windsurf') {
      const windsurfPath = join(targetDir, '.windsurfrules');
      if (existsSync(windsurfPath)) {
        const content = readFileSync(windsurfPath, 'utf-8');
        const isPackGenerated = (content.includes('Windsurf') && content.includes(manifest.name)) || options.force;
        if (isPackGenerated) {
          unlinkSync(windsurfPath);
          console.log(`  ${chalk.red('✗ Removed:')} .windsurfrules`);
          itemsCleaned++;
        }
      }
    }

    // --- Clean Roo-Code / Cline ---
    if (targetClient === 'all' || targetClient === 'roo' || targetClient === 'cline') {
      const rooModesPath = join(targetDir, '.roomodes');
      if (existsSync(rooModesPath)) {
        unlinkSync(rooModesPath);
        console.log(`  ${chalk.red('✗ Removed:')} .roomodes`);
        itemsCleaned++;
      }
      if (serverIds.length > 0) {
        const removed = unmergeMcpConfig(join(targetDir, '.roo', 'mcp.json'), serverIds);
        if (removed > 0) {
          console.log(`  ${chalk.red('✗ Pruned:')} ${removed} servers from .roo/mcp.json`);
          itemsCleaned += removed;
        }
      }
    }

    // --- Clean OpenCode ---
    if (targetClient === 'all' || targetClient === 'opencode') {
      const opencodePath = join(targetDir, 'opencode.json');
      if (existsSync(opencodePath) && serverIds.length > 0) {
        try {
          const cfg = JSON.parse(readFileSync(opencodePath, 'utf-8'));
          let removed = 0;
          if (cfg.mcp) {
            for (const id of serverIds) {
              if (cfg.mcp[id]) {
                delete cfg.mcp[id];
                removed++;
              }
            }
            if (removed > 0) {
              writeFileSync(opencodePath, JSON.stringify(cfg, null, 2), 'utf-8');
              console.log(`  ${chalk.red('✗ Pruned:')} ${removed} servers from opencode.json`);
              itemsCleaned += removed;
            }
          }
        } catch {}
      }
    }

    // --- Clean Agent Skills ---
    if (manifest.skills && Array.isArray(manifest.skills)) {
      for (const skill of manifest.skills) {
        const skillName = skill.name || skill.id;
        const targetSkillDir = join(targetDir, 'skills', skillName);
        if (existsSync(targetSkillDir)) {
          rmSync(targetSkillDir, { recursive: true, force: true });
          console.log(`  ${chalk.red('✗ Removed skill:')} skills/${skillName}`);
          itemsCleaned++;
        }
      }
      const rootSkillsDir = join(targetDir, 'skills');
      try {
        if (existsSync(rootSkillsDir)) rmdirSync(rootSkillsDir);
      } catch {}
    }

    // --- Clean Knowledge Base ---
    const targetKnowledgeDir = join(targetDir, '.packai', 'knowledge');
    if (existsSync(targetKnowledgeDir)) {
      rmSync(targetKnowledgeDir, { recursive: true, force: true });
      console.log(`  ${chalk.red('✗ Removed knowledge:')} .packai/knowledge/`);
      itemsCleaned++;
      try {
        const packaiDir = join(targetDir, '.packai');
        if (existsSync(packaiDir)) rmdirSync(packaiDir);
      } catch {}
    }

    console.log();
    if (itemsCleaned > 0) {
      log.success(`Cleaned ${itemsCleaned} items cleanly without touching unrelated project files.`);
    } else {
      console.log(chalk.dim(`No provisioned assets found to clean.`));
    }
    console.log();

  } catch (err) {
    log.error(err.message);
    process.exit(1);
  }
}
