import { readFileSync, writeFileSync, existsSync, unlinkSync, rmdirSync } from 'fs';
import { resolve, join } from 'path';
import { loadManifest } from './validate.js';
import { log } from '../utils/logger.js';
import chalk from 'chalk';

/**
 * Remove pack MCP servers from an MCP config file, preserving others.
 */
function unmergeMcpConfig(filePath, serverIds) {
  if (!existsSync(filePath)) return 0;

  try {
    const config = JSON.parse(readFileSync(filePath, 'utf-8'));
    if (!config.mcpServers) return 0;

    let removed = 0;
    for (const id of serverIds) {
      if (config.mcpServers[id]) {
        delete config.mcpServers[id];
        removed++;
      }
    }

    if (removed > 0) {
      writeFileSync(filePath, JSON.stringify(config, null, 2), 'utf-8');
    }
    return removed;
  } catch {
    return 0;
  }
}

export async function cleanCommand(path, options = {}) {
  try {
    const { manifest } = loadManifest(path);
    const targetDir = resolve(options.cwd || '.');
    const targetClient = (options.target || 'all').toLowerCase();

    console.log();
    console.log(chalk.bold.red(`🧹 AIPack Safe De-Provisioner: ${manifest.name}`));
    console.log(chalk.dim(`Cleaning from: ${targetDir}`));
    console.log();

    let itemsCleaned = 0;
    const serverIds = (manifest.tools?.mcp_servers || []).map(s => s.id || s.name);

    // --- Clean Claude Code / Desktop ---
    if (targetClient === 'all' || targetClient === 'claude') {
      // 1. Subagents
      if (manifest.agents) {
        for (const agent of manifest.agents) {
          const agentFile = join(targetDir, '.claude', 'agents', `${agent.id}.md`);
          if (existsSync(agentFile)) {
            unlinkSync(agentFile);
            console.log(`  ${chalk.red('✗ Removed:')} .claude/agents/${agent.id}.md`);
            itemsCleaned++;
          }
        }

        // Try removing agents directory if empty
        const agentsDir = join(targetDir, '.claude', 'agents');
        try {
          if (existsSync(agentsDir)) rmdirSync(agentsDir);
        } catch {
          // not empty, that's fine
        }
      }

      // 2. CLAUDE.md (safe check)
      const claudeMdPath = join(targetDir, 'CLAUDE.md');
      if (existsSync(claudeMdPath)) {
        const content = readFileSync(claudeMdPath, 'utf-8');
        const isPackGenerated = (content.includes('aipack') && content.includes(manifest.name)) || options.force;
        if (isPackGenerated) {
          unlinkSync(claudeMdPath);
          console.log(`  ${chalk.red('✗ Removed:')} CLAUDE.md`);
          itemsCleaned++;
        } else {
          console.log(`  ${chalk.yellow('⚠ Skipped:')} CLAUDE.md (contains modifications or not generated by this pack. Use --force to delete)`);
        }
      }

      // 3. MCP servers in .claude/settings.json
      if (serverIds.length > 0) {
        const removed = unmergeMcpConfig(join(targetDir, '.claude', 'settings.json'), serverIds);
        if (removed > 0) {
          console.log(`  ${chalk.red('✗ Pruned:')} ${removed} servers from .claude/settings.json`);
          itemsCleaned += removed;
        }
      }
    }

    // --- Clean Cursor ---
    if (targetClient === 'all' || targetClient === 'cursor') {
      const cursorrulesPath = join(targetDir, '.cursorrules');
      if (existsSync(cursorrulesPath)) {
        const content = readFileSync(cursorrulesPath, 'utf-8');
        const isPackGenerated = (content.includes('aipack') && content.includes(manifest.name)) || options.force;
        if (isPackGenerated) {
          unlinkSync(cursorrulesPath);
          console.log(`  ${chalk.red('✗ Removed:')} .cursorrules`);
          itemsCleaned++;
        } else {
          console.log(`  ${chalk.yellow('⚠ Skipped:')} .cursorrules (contains custom modifications. Use --force to delete)`);
        }
      }

      if (serverIds.length > 0) {
        const removed = unmergeMcpConfig(join(targetDir, '.cursor', 'mcp.json'), serverIds);
        if (removed > 0) {
          console.log(`  ${chalk.red('✗ Pruned:')} ${removed} servers from .cursor/mcp.json`);
          itemsCleaned += removed;
        }
      }
    }

    console.log();
    if (itemsCleaned > 0) {
      log.success(`Cleaned ${itemsCleaned} items cleanly without touching unrelated project files.`);
    } else {
      console.log(chalk.dim(`No provisioned assets found to clean.`));
    }
    console.log();

  } catch (err) {
    log.error(err.message);
    process.exit(1);
  }
}
