import { readFileSync } from 'fs';
import { join } from 'path';

/**
 * Universal AGENTS.md Exporter
 * Conforms to Linux Foundation Agentic AI Foundation (AAIF) specification.
 * Natively parsed by GitHub Copilot, Cursor, Zed, Aider, Gemini CLI, and Codex.
 */
export function exportToAgentsMd(manifest, packDir) {
  let output = '';

  // Header
  output += `# AGENTS.md\n\n`;
  output += `> Universal Agent Architecture: **${manifest.name}** v${manifest.version}\n`;
  output += `> Standard: Linux Foundation AAIF Specification | Generated by aipack\n\n`;
  output += `${manifest.description}\n\n`;
  output += `---\n\n`;

  // System Persona
  const persona = manifest.persona;
  if (persona) {
    output += '## 🎭 Identity & Persona\n\n';
    if (persona.file) {
      try {
        output += readFileSync(join(packDir, persona.file), 'utf-8') + '\n\n';
      } catch {
        output += `<!-- Warning: Could not read ${persona.file} -->\n\n`;
      }
    } else {
      if (persona.role) output += `* **Primary Role:** ${persona.role}\n`;
      if (persona.tone) output += `* **Communication Tone:** ${persona.tone}\n`;
      if (persona.expertise && persona.expertise.length > 0) {
        output += `* **Core Expertise:** ${persona.expertise.join(', ')}\n`;
      }
      if (persona.language) output += `* **Working Language:** ${persona.language}\n`;
      if (persona.instructions) output += `\n${persona.instructions}\n\n`;
      output += '\n';
    }
  }

  // Rules & Behavioral Constraints
  const rules = manifest.rules;
  if (rules) {
    output += '## 📋 Operational Directives & Constraints\n\n';
    if (rules.file) {
      try {
        output += readFileSync(join(packDir, rules.file), 'utf-8') + '\n\n';
      } catch {
        output += `<!-- Warning: Could not read ${rules.file} -->\n\n`;
      }
    } else if (rules.items) {
      for (const rule of rules.items) {
        output += `- [ ] ${rule}\n`;
      }
      output += '\n';
    }
  }

  // Multi-Agent Workforce (Level 3)
  if (manifest.agents && manifest.agents.length > 0) {
    output += '## 👥 Multi-Agent Workforce\n\n';
    output += 'This system operates with a specialized, context-isolated multi-agent workforce:\n\n';

    for (const agent of manifest.agents) {
      output += `### Agent: ${agent.name} (\`${agent.id}\`)\n\n`;
      if (agent.description) output += `* **Description:** ${agent.description}\n`;
      if (agent.model_preference) output += `* **Recommended Model:** \`${agent.model_preference}\`\n`;

      if (agent.persona?.file) {
        try {
          output += '\n' + readFileSync(join(packDir, agent.persona.file), 'utf-8') + '\n\n';
        } catch {
          if (agent.persona.instructions) output += '\n' + agent.persona.instructions + '\n\n';
        }
      } else if (agent.persona?.instructions) {
        output += '\n' + agent.persona.instructions + '\n\n';
      }

      if (agent.rules?.items) {
        output += `* **Agent Directives:**\n`;
        for (const r of agent.rules.items) output += `  - ${r}\n`;
        output += '\n';
      }
    }
  }

  // Orchestration & Routing
  if (manifest.workflow) {
    output += '## 🔄 Orchestration & Routing Protocol\n\n';
    if (manifest.workflow.entry) {
      output += `* **Coordinator / Entrypoint:** \`${manifest.workflow.entry}\`\n`;
    }

    if (manifest.workflow.shared_context) {
      const sc = manifest.workflow.shared_context;
      output += `* **Shared Context Limit:** ${sc.max_history_messages || 20} messages across handoffs.\n`;
    }

    if (manifest.workflow.routes && manifest.workflow.routes.length > 0) {
      output += '\n### State Machine Routing Matrix\n\n';
      output += '| Source Agent | Target Agent | Intent / Trigger | Fallback |\n';
      output += '| :--- | :--- | :--- | :---: |\n';
      for (const r of manifest.workflow.routes) {
        output += `| \`${r.from}\` | \`${r.to}\` | ${r.condition} | ${r.fallback ? 'Yes' : 'No'} |\n`;
      }
      output += '\n';
    }
  }

  // MCP & External Tools
  if (manifest.tools?.mcp_servers && manifest.tools.mcp_servers.length > 0) {
    output += '## 🛠 Tool & Capability Integration (MCP)\n\n';
    output += '| Server ID | Source / Package | Description |\n';
    output += '| :--- | :--- | :--- |\n';
    for (const s of manifest.tools.mcp_servers) {
      output += `| \`${s.name || s.id}\` | \`${s.source || s.command || 'npx'}\` | ${s.description || '-'} |\n`;
    }
    output += '\n';
  }

  // Sandboxing & Security Constraints
  if (manifest.requirements?.sandbox) {
    const sb = manifest.requirements.sandbox;
    output += '## 🔒 Execution Environment & Sandboxing\n\n';
    output += `* **Sandbox Provider:** \`${sb.provider || 'docker'}\`\n`;
    if (sb.isolation_level) output += `* **Isolation Level:** \`${sb.isolation_level}\`\n`;
    if (sb.network) output += `* **Network Access Policy:** \`${sb.network}\`\n`;
    if (sb.image) output += `* **Container Image:** \`${sb.image}\`\n`;
    output += '\n';
  }

  return output.trim() + '\n';
}
