import { readFileSync } from 'fs';
import { join } from 'path';

export function exportToCursor(manifest, packDir) {
  let output = '';

  // Header
  output += `# AI Rules for ${manifest.name}\n`;
  output += `# Generated by aipack v${manifest.version}\n`;
  output += `# ${manifest.description}\n\n`;

  // Persona
  output += buildPersonaSection(manifest, packDir);

  // Rules
  output += buildRulesSection(manifest, packDir);

  // Knowledge (embedded only)
  output += buildKnowledgeSection(manifest, packDir);

  return output.trim() + '\n';
}

function buildPersonaSection(manifest, packDir) {
  let section = '';
  const persona = manifest.persona;
  if (!persona) return section;

  section += '## Persona\n\n';

  if (persona.file) {
    try {
      section += readFileSync(join(packDir, persona.file), 'utf-8') + '\n\n';
    } catch {
      section += `<!-- Error: Could not read ${persona.file} -->\n\n`;
    }
  } else {
    if (persona.role) section += `You are a ${persona.role}.\n\n`;
    if (persona.tone) section += `Tone: ${persona.tone}\n\n`;
    if (persona.expertise && persona.expertise.length > 0) {
      section += `Expertise: ${persona.expertise.join(', ')}\n\n`;
    }
    if (persona.instructions) section += persona.instructions + '\n\n';
  }

  return section;
}

function buildRulesSection(manifest, packDir) {
  let section = '';
  const rules = manifest.rules;
  if (!rules) return section;

  section += '## Rules\n\n';

  if (rules.file) {
    try {
      section += readFileSync(join(packDir, rules.file), 'utf-8') + '\n\n';
    } catch {
      section += `<!-- Error: Could not read ${rules.file} -->\n\n`;
    }
  } else if (rules.items && rules.items.length > 0) {
    for (const rule of rules.items) {
      section += `- ${rule}\n`;
    }
    section += '\n';
  }

  return section;
}

function buildKnowledgeSection(manifest, packDir) {
  let section = '';
  const knowledge = manifest.knowledge;
  if (!knowledge || knowledge.length === 0) return section;

  const embedded = knowledge.filter(k => k.type === 'embedded');
  if (embedded.length === 0) return section;

  section += '## Reference Knowledge\n\n';

  for (const k of embedded) {
    section += `### ${k.name}\n\n`;
    if (k.description) section += `${k.description}\n\n`;
    if (k.path) {
      try {
        const content = readFileSync(join(packDir, k.path), 'utf-8');
        section += content + '\n\n';
      } catch {
        section += `<!-- Error: Could not read ${k.path} -->\n\n`;
      }
    }
  }

  return section;
}
