import { readFileSync } from 'fs';
import { join } from 'path';

export function exportToCursor(manifest, packDir) {
  let output = '';

  // Header
  output += `# AI Rules for ${manifest.name}\n`;
  output += `# Generated by aipack v${manifest.version}\n`;
  output += `# ${manifest.description}\n\n`;

  // Persona
  output += buildPersonaSection(manifest, packDir);

  // Rules
  output += buildRulesSection(manifest, packDir);

  // Knowledge (embedded only)
  output += buildKnowledgeSection(manifest, packDir);

  // Level 3: Multi-Agent Architecture
  output += buildAgentsSection(manifest, packDir);

  // Level 3: Workflow Routing
  output += buildWorkflowSection(manifest);

  return output.trim() + '\n';
}

function buildPersonaSection(manifest, packDir) {
  let section = '';
  const persona = manifest.persona;
  if (!persona) return section;

  section += '## Persona\n\n';

  if (persona.file) {
    try {
      section += readFileSync(join(packDir, persona.file), 'utf-8') + '\n\n';
    } catch {
      section += `<!-- Error: Could not read ${persona.file} -->\n\n`;
    }
  } else {
    if (persona.role) section += `You are a ${persona.role}.\n\n`;
    if (persona.tone) section += `Tone: ${persona.tone}\n\n`;
    if (persona.expertise && persona.expertise.length > 0) {
      section += `Expertise: ${persona.expertise.join(', ')}\n\n`;
    }
    if (persona.instructions) section += persona.instructions + '\n\n';
  }

  return section;
}

function buildRulesSection(manifest, packDir) {
  let section = '';
  const rules = manifest.rules;
  if (!rules) return section;

  section += '## Rules\n\n';

  if (rules.file) {
    try {
      section += readFileSync(join(packDir, rules.file), 'utf-8') + '\n\n';
    } catch {
      section += `<!-- Error: Could not read ${rules.file} -->\n\n`;
    }
  } else if (rules.items && rules.items.length > 0) {
    for (const rule of rules.items) {
      section += `- ${rule}\n`;
    }
    section += '\n';
  }

  return section;
}

function buildKnowledgeSection(manifest, packDir) {
  let section = '';
  const knowledge = manifest.knowledge;
  if (!knowledge || knowledge.length === 0) return section;

  const embedded = knowledge.filter(k => k.type === 'embedded');
  if (embedded.length === 0) return section;

  section += '## Reference Knowledge\n\n';

  for (const k of embedded) {
    section += `### ${k.name}\n\n`;
    if (k.description) section += `${k.description}\n\n`;
    if (k.path) {
      try {
        const content = readFileSync(join(packDir, k.path), 'utf-8');
        section += content + '\n\n';
      } catch {
        section += `<!-- Error: Could not read ${k.path} -->\n\n`;
      }
    }
  }

  return section;
}

function buildAgentsSection(manifest, packDir) {
  let section = '';
  const agents = manifest.agents;
  if (!agents || agents.length === 0) return section;

  section += '## Multi-Agent Workforce (Level 3)\n\n';
  section += 'This pack configures specialized agent personas for this project:\n\n';

  for (const agent of agents) {
    section += `### ${agent.name} (\`${agent.id}\`)\n\n`;
    if (agent.description) section += `${agent.description}\n\n`;
    if (agent.model_preference) section += `Model Tier: ${agent.model_preference}\n\n`;

    if (agent.persona?.file) {
      try {
        section += readFileSync(join(packDir, agent.persona.file), 'utf-8') + '\n\n';
      } catch {
        if (agent.persona.instructions) section += agent.persona.instructions + '\n\n';
      }
    } else if (agent.persona?.instructions) {
      section += agent.persona.instructions + '\n\n';
    }
  }

  return section;
}

function buildWorkflowSection(manifest) {
  let section = '';
  const workflow = manifest.workflow;
  if (!workflow) return section;

  section += '## Task Routing Logic\n\n';
  if (workflow.entry) {
    section += `Primary Entrypoint: \`${workflow.entry}\`\n\n`;
  }

  if (workflow.routes && workflow.routes.length > 0) {
    section += 'Routing Rules:\n';
    for (const r of workflow.routes) {
      section += `- Route from \`${r.from}\` to \`${r.to}\` when: ${r.condition}\n`;
    }
    section += '\n';
  }

  return section;
}
